[package]
name = "mcsp-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
figlet-rs = "0.1.5"
inquire = { version = "0.6.2", features = ["date"] }
