services:
  dev-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8085:18888"
    expose:
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "microscope_boilerplate_data"
        read_only: false
      - type: "bind"
        target: "/docker-entrypoint-initdb.d/init.sql"
        source: "/Users/bhtz/workspace/repositories/Microscope.Boilerplate/src/templates/dotnet/services/modular-monolith/IAC/Docker/Postgres/init.sql"
        read_only: false
    networks:
      - "aspire"
  keycloak:
    image: "quay.io/keycloak/keycloak:22.0"
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "microscope"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/mcsp_identity"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "root"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_LOG_LEVEL: "INFO"
    expose:
      - "8080"
    volumes:
      - type: "bind"
        target: "/opt/keycloak/data/import/realm-export.json"
        source: "/Users/bhtz/workspace/repositories/Microscope.Boilerplate/src/templates/dotnet/services/modular-monolith/IAC/Docker/Keycloak/realm-export.json"
        read_only: false
      - type: "bind"
        target: "/opt/keycloak/themes/microscope"
        source: "/Users/bhtz/workspace/repositories/Microscope.Boilerplate/src/templates/dotnet/services/modular-monolith/IAC/Docker/Keycloak/Themes/microscope/"
        read_only: false
    depends_on:
      postgres:
        condition: "service_started"
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://dev-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "${API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
      keycloak:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  microscope_boilerplate_data:
    driver: "local"
